# Generated by Django 5.1 on 2024-08-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
